; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Mon Jun 14 2021 12:17:56 GMT+0200 (hora de verano de Europa central)
; Wait for set temperatures to be reached
M116 P0

